name: Animal Farm NodeJS CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to repository
      uses: actions/checkout@v2
    - name: Install Dependencies Node js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Run Yarn
      run: yarn 
    - name: Run Tests
      run: yarn test
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge feature into master 
        run: |
          git merge --no-ff origin/feat-newanimal